# Generated by Django 4.0.3 on 2022-05-13 11:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_aggregator', '0006_rename_userprofile_usercategories_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCategories',
            new_name='UserProfile',
        ),
    ]
