# Generated by Django 4.0.3 on 2022-05-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_aggregator', '0009_remove_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(blank=True, max_length=255, verbose_name='Источник'),
        ),
    ]
