# Generated by Django 4.0.3 on 2022-05-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_aggregator', '0010_article_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
